.catalog:
  name: "ELK Demo Stack"
  version: 1
  description: "All the things"


logstash:
  scale: 1
  start_on_create: true
elasticsearch:
  scale: 1
  start_on_create: true
kibana:
  scale: 1
  start_on_create: true
