name: Nutanix Volume Driver
description: |
  Volume Driver for Nutanix volume group
version: 1
category: Storage
labels:
  io.rancher.certified: nutanix
  io.rancher.orchestration.supported: 'cattle,swarm'
